apiVersion: 1
playlists:
  - name: 'Monitoring Overview'
    interval: 30s
    items:
      - type: dashboard_by_title
        value: 'Node Exporter Full'
      - type: dashboard_by_title
        value: 'MySQL Overview'
      - type: dashboard_by_title
        value: 'NGINX'
      - type: dashboard_by_title
        value: 'Prometheus 2.0 Stats'
