apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: wp
data:
  nginx.conf: |
    upstream wordpress_backend {
        server wordpress:80;
    }

    server {
        listen 80;
        server_name localhost;

        location / {
            proxy_pass http://wordpress_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /stub_status {
            stub_status;
            access_log off;
        }
    }

    # HTTPS block (works if certs exist)
    server {
        listen 443 ssl;
        server_name localhost;

        ssl_certificate /etc/nginx/certs/tls.crt;
        ssl_certificate_key /etc/nginx/certs/tls.key;

        location / {
            proxy_pass http://wordpress_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /stub_status {
            stub_status;
            access_log off;
        }
    }