apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: wp
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mysql
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-pv
  namespace: wp
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/wordpress
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup-pv
  namespace: wp
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/backups