apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: wp
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3M=
  MYSQL_USER: d3B1c2Vy
  MYSQL_PASSWORD: d3BwYXNz
  MYSQL_DATABASE: d29yZHByZXNz